name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install
        run: npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Lint
        run: npm run lint --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present

      - name: Test
        run: npm test --workspaces --if-present
